### ISSUE TITLE
Support custom attributes for trees created via the AbstractTrees interface

### ISSUE THREAD

**Issue by ebalaban** [sisl/D3Trees.jl#20]
Right now there is no way to specify tree attributes (such as `init_expand`, `title`, etc) if one is using the `D3Tree(node; detect_repeat=true)` constructor, i.e., the `AbstractTrees` interface. To help with my own debugging, I went ahead and implemented this functionality and created a pull request for it: #19.

In it, the `D3Tree(node; ...)` constructor will now take the same keyword arguments as `D3Tree(children, <keyword arguments>)`, in addition to detect_repeat. Some of the arguments won't be very useful for the `AbstractTrees` interface (`text`, `tooltip`, `style`, and `link_style`), but that's probably not a big deal.

Additionally, I'd like to suggest two new D3Trees API functions, `style()` and `link_style()`, that can help set node and link attributes:

```julia
style(node)::String = ""
link_style(node1, node2)::String = ""
```
Alternatively, we could propose adding them to the `AbstractTrees` API. What do you think?

**Comment by ebalaban** [comment]
I goofed on `link_style()` definition and use in the first commit, as it turned out.  It should be defined as

```julia
link_style(node)::String = ""
```
and describe the attributes for the link **leading** to `node`.

**Comment by zsunberg** [comment]
Thanks for proposing this and making the PR!

I don't think these functions really belong in the AbstractTrees interface because they only relate to *displaying* the tree.
