### ISSUE TITLE
Specifying attributes as functions

### ISSUE THREAD

**Issue by zsunberg** [sisl/D3Trees.jl#3]
@mykelk had the idea of specifying the attributes of each node as a function, i.e.
```julia
f(i) = isodd(i) ? "fill:blue" : "fill:red"
D3Tree(children, style=f)
```
I don't think this is necessary right now because it's easy enough to do
```julia
D3Tree(children, style=[f(i) for i in 1:length(children)])
```
but we could add it if people want it. I just want to maintain as little code as possible.

**Comment by mykelk** [comment]
Yeah, that's fine.
