### ISSUE TITLE
Save the D3Tree as html file (improvement?).

### ISSUE THREAD

**Issue by Piaktipik** [sisl/D3Trees.jl#30]
It will be great to have an example of how to store a D3Tree in HTML.

For example, instead of:
inchrome(D3Tree(info[:tree], init_expand=0, title="TreeStep-$c" ))

Something like:

saveTree(D3Tree(info[:tree], init_expand=0, title="TreeStep-$c" ), pathHTLMOutputFile)

So the tree can later be inspected using a particular browser.

**Comment by nsajko** [comment]
@Piaktipik I agree with this feature request, but FTR I think that a simple workaround exists, do something like this:
```
inbrowser(d3tree, "echo")
```

As a result, `echo` should echo its argument (the URL) back to your terminal stdout.

**Comment by Piaktipik** [comment]
@nsajko, that is a great workaround. With the link, it will be a matter of copying it from there (/tmp/jl_6l5v9e/tree.html) to the path of interest, I will do that, thank you!
